# Generated by Django 2.2.7 on 2020-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when instance was created.', verbose_name='create time')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Time when instance was deleted.', null=True, verbose_name='delete time')),
                ('last_update_at', models.DateTimeField(auto_now=True, help_text='Time when isinstance was updted.', null=True, verbose_name='last update')),
                ('name', models.TextField(null=True)),
                ('api', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
